### PR TITLE
issue/18

### PR DESCRIPTION
**Pull request by mstruensee**
remove test-id from attributes that are objects, where any key in the object, is a test-id.

### CODE REVIEW

**Comment by mstruensee** [comment]
I was hoping you would catch them small things, my formatter is opposite of yours lol ... was hoping there was a linter to fix it for, my eyes are not as good as they once were lol.

**Comment by coderas** [comment]
Thanks, I'll take a detailed look in the next 24hrs and release this is possible.

Thanks for the quick response.

**Comment by mstruensee** [comment]
cool thanks, lmk when publish so I can update :)

**Comment by mstruensee** [comment]
don't want to sound pushy, but got any ETA on this?

**Comment by coderas** [comment]
Oh, sorry! Life got in the way - actually will release later today.

**Comment by coderas** [comment]
Thanks Nice work - releasing now.

**Comment by mstruensee** [comment]
np! ... sweet thanks!

**Pull request merged**
